/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.PreguntasControlador;
import Modelos.Pregunta;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class PreguntasVista extends javax.swing.JFrame {

    /**
     * Creates new form VistasdelosCursos
     */
    private PreguntasControlador controlador;
    private int contador=1;
    
    public PreguntasVista(PreguntasControlador controlador) {
        this.controlador=controlador;
        initComponents();
        setLocationRelativeTo(null);
    
        buttonGroup1 = new ButtonGroup();
        buttonGroup1.add(radioBtn1);
        buttonGroup1.add(radioBtn2);
        buttonGroup1.add(radioBtn3);
    }
    
    public void mostrarInfo(){
        Pregunta pregunta=controlador.getPreguntas().get(contador-1);
        
        lblNumEjercicio.setText("Ejercicio "+contador);
        lblEnunciado.setText(pregunta.getEnunciado());
        radioBtn1.setEnabled(true);
        radioBtn2.setEnabled(true);
        radioBtn3.setEnabled(true);            
        radioBtn1.setText(pregunta.getAlternativas()[0]);
        radioBtn2.setText(pregunta.getAlternativas()[1]);
        radioBtn3.setText(pregunta.getAlternativas()[2]);
        lblCorrecta.setText(pregunta.getAlternativas()[pregunta.getRespuesta()-1]);
        
        if(!pregunta.isCompleto()){
            lblCorrecta.setVisible(false);
            lblRespuesta.setVisible(false);  
        }else{
            radioBtn1.setEnabled(false);
            radioBtn2.setEnabled(false);
            radioBtn3.setEnabled(false);            
        }
    }
    
    public void mostrarAlerta(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void verificarRespuesta(int res){
        if(controlador.getPreguntas().get(contador-1).getRespuesta()==res){
            mostrarAlerta("Respuesta correcta");
            
            btnEntregar.setText("SIGUIENTE");
            lblRespuesta.setVisible(true);
            lblCorrecta.setVisible(true);
            radioBtn1.setEnabled(false);
            radioBtn2.setEnabled(false);
            radioBtn3.setEnabled(false);

            controlador.getPreguntas().get(contador-1).setCompleto(true);                       
        }else{
            mostrarAlerta("Respuesta incorrecta. Intenta nuevamente");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNumEjercicio = new javax.swing.JLabel();
        lblEnunciado = new javax.swing.JLabel();
        radioBtn1 = new javax.swing.JRadioButton();
        radioBtn2 = new javax.swing.JRadioButton();
        radioBtn3 = new javax.swing.JRadioButton();
        lblRespuesta = new javax.swing.JLabel();
        lblCorrecta = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEntregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setBackground(new java.awt.Color(255, 51, 51));
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Degradado1.jpg"))); // NOI18N

        lblNumEjercicio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblNumEjercicio.setText("Ejercicio");

        lblEnunciado.setText("Enunciado");

        radioBtn1.setText("Alternativa 1");

        radioBtn2.setText("Alternativa 2");

        radioBtn3.setText("Alternativa 3");

        lblRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRespuesta.setText("RESPUESTA:");

        lblCorrecta.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Degradado1.jpg"))); // NOI18N

        btnEntregar.setBackground(new java.awt.Color(102, 255, 102));
        btnEntregar.setText("ENTREGAR");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnunciado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumEjercicio)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRespuesta)
                        .addGap(18, 18, 18)
                        .addComponent(lblCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnRegresar)
                            .addGap(18, 18, 18)
                            .addComponent(btnEntregar))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(radioBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(radioBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumEjercicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioBtn1)
                .addGap(50, 50, 50)
                .addComponent(radioBtn2)
                .addGap(53, 53, 53)
                .addComponent(radioBtn3)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespuesta)
                    .addComponent(lblCorrecta))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnEntregar))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        controlador.mostrarTemas();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
        if(controlador.getPreguntas().get(contador-1).isCompleto()){
            btnEntregar.setText("ENTREGAR");
            controlador.aumentarProgreso(contador);
            contador++;
           
            if(contador<=controlador.getPreguntas().size()) mostrarInfo();   
            else{
                contador=1;
                controlador.mostrarTemas();
            }
            
        }else{
            if (radioBtn1.isSelected()) {
                verificarRespuesta(1);
            } else if (radioBtn2.isSelected()) {
                verificarRespuesta(2);
            } else if (radioBtn3.isSelected()) {
                verificarRespuesta(3);
            }else{
                mostrarAlerta("No ha seleccionado ninguna alternativa");
            }       
        }      
    }//GEN-LAST:event_btnEntregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreguntasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreguntasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreguntasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreguntasVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorrecta;
    private javax.swing.JLabel lblEnunciado;
    private javax.swing.JLabel lblNumEjercicio;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JRadioButton radioBtn1;
    private javax.swing.JRadioButton radioBtn2;
    private javax.swing.JRadioButton radioBtn3;
    // End of variables declaration//GEN-END:variables

    /*private static class ButtonGroup1 extends ButtonGroup {

        public ButtonGroup1() {
        }
    }*/
}
