/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.TemarioControlador;
import Modelos.Tema;
import java.util.List;
import java.util.stream.IntStream;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class TemarioVista extends javax.swing.JFrame {

    /**
     * Creates new form TemarioRM
     */
    private TemarioControlador controlador;
    private List<JButton> botones;
    
    public TemarioVista(TemarioControlador controlador) {
        this.controlador=controlador;
        initComponents();
        
        botones=List.of(btnTema1, btnTema2, btnTema3, btnTema4,btnTema5);
    }
    
    /*public void mostrarInfo(String titulo){
        lblTituloCurso.setText(titulo);
        ocultarInfo();
        
        for (int i = 0; i < botones.size(); i++) {
            JButton boton=botones.get(i);
            Tema tema=null;
            
            if(i<controlador.getTemas().size()) tema=controlador.getTemas().get(i);               
            
            if(tema!=null){
                boton.setVisible(true);
                boton.setText(tema.getTitulo());
            }
            //if(boton.getText().isEmpty()) boton.setVisible(false);
        }
    }*/
    
    public void mostrarInfo(String titulo){
        lblTituloCurso.setText(titulo);
        ocultarInfo();
        
        IntStream.range(0, botones.size()).forEach(i -> {
            JButton boton = botones.get(i);
            Tema tema = null;

            if (i < controlador.getTemas().size()) {
                tema = controlador.getTemas().get(i);
            }

            if (tema != null) {
                boton.setVisible(true);
                boton.setText(tema.getTitulo());
            }
        });    
    }
    public void ocultarInfo(){
        /*for (JButton b : botones) {
            b.setVisible(false);
        }*/
        botones.forEach(b -> b.setVisible(false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTituloCurso = new javax.swing.JLabel();
        btnTema4 = new javax.swing.JButton();
        btnTema3 = new javax.swing.JButton();
        btnTema2 = new javax.swing.JButton();
        btnTema1 = new javax.swing.JButton();
        btnTema5 = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CUESTIONARIO");

        lblTituloCurso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTituloCurso.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Degradado1.jpg"))); // NOI18N
        lblTituloCurso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnTema4.setBackground(new java.awt.Color(204, 204, 204));
        btnTema4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTema4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTema4ActionPerformed(evt);
            }
        });

        btnTema3.setBackground(new java.awt.Color(204, 204, 204));
        btnTema3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTema3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTema3ActionPerformed(evt);
            }
        });

        btnTema2.setBackground(new java.awt.Color(204, 204, 204));
        btnTema2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTema2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTema2ActionPerformed(evt);
            }
        });

        btnTema1.setBackground(new java.awt.Color(204, 204, 204));
        btnTema1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTema1.setToolTipText("");
        btnTema1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTema1ActionPerformed(evt);
            }
        });

        btnTema5.setBackground(new java.awt.Color(204, 204, 204));
        btnTema5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTema5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTema5ActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(153, 204, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTema2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(btnTema3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTema1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, Short.MAX_VALUE)
                            .addComponent(btnTema4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTema5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(lblTituloCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnTema1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnTema2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnTema3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnTema4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnTema5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        controlador.mostrarTablero();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnTema1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTema1ActionPerformed
        // TODO add your handling code here:
        controlador.mostrarPreguntas(0);
    }//GEN-LAST:event_btnTema1ActionPerformed

    private void btnTema2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTema2ActionPerformed
        // TODO add your handling code here:
        controlador.mostrarPreguntas(1);
    }//GEN-LAST:event_btnTema2ActionPerformed

    private void btnTema3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTema3ActionPerformed
        // TODO add your handling code here:
        controlador.mostrarPreguntas(2);
    }//GEN-LAST:event_btnTema3ActionPerformed

    private void btnTema4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTema4ActionPerformed
        // TODO add your handling code here:
        controlador.mostrarPreguntas(3);
    }//GEN-LAST:event_btnTema4ActionPerformed

    private void btnTema5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTema5ActionPerformed
        // TODO add your handling code here:
        controlador.mostrarPreguntas(4);
    }//GEN-LAST:event_btnTema5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temario().setVisible(true);
            }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temario().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnTema1;
    private javax.swing.JButton btnTema2;
    private javax.swing.JButton btnTema3;
    private javax.swing.JButton btnTema4;
    private javax.swing.JButton btnTema5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTituloCurso;
    // End of variables declaration//GEN-END:variables
}
